POST localhost:9999/registerWithEmail
Content-Type: application/json

{
  "dateOfBirth" : "2000-10-10",
  "email" : "petur@abv.bg",
  "password" : "Petur@123",
  "confirmPassword" : "Petur@123"
}

###
POST localhost:9999/loginWithEmail
Content-Type: application/json

{
  "email" : "petur@abv.bg",
  "password" : "Petur@123"
}

###
POST localhost:9999/forgottenPassword
Content-Type: application/json

{
  "email" : "petur@abv.bg"
}

###
PUT localhost:9999/forgottenPassword/changePassword
Content-Type: application/json

{
  "password" : "Petur@1234",
  "confirmPassword" : "Petur@1234"
}

###
POST localhost:9999/users/1/setUsername
Content-Type: application/json

{
  "id" : "1",
  "username" : "MasterPetur",
  "name" : "Petur Petrov"
}

###
PUT localhost:9999/users/edit
Content-Type: application/json

{
"id" : "1",
"username" : "MasterPetur",
"name" : "Petur Stoqnov",
"email" : "peturveliki@abv.bg",
"phoneNumber" : "+359889376648",
"password" : "Petur@1234",
"newPassword" : "Petur@12345",
"confirmNewPassword" : "Petur@12345",
"description" : "Hi, I am Petur from Sofia!"
}

