POST localhost:9999/registerWithEmail
Content-Type: application/json

{
  "dateOfBirth" : "2000-10-10",
  "email" : "mario@gmail.com",
  "password" : "Pesho123@",
  "confirmPassword" : "Pesho123@"
}
###
POST localhost:9999/registerWithPhone
Content-Type: application/json

{
  "dateOfBirth" : "2000-10-10",
  "phoneNumber" : "0888456789",
  "password" : "Pesho@12345",
  "confirmPassword" : "Pesho@12345"
}

###
POST localhost:9999/loginWithEmail
Content-Type: application/json

{
  "email" : "tomi@abv.bg",
  "password" : "Pesho@12345"

}

###
POST localhost:9999/loginWithPhone
Content-Type: application/json

{
  "phoneNumber" : "0897897897",
  "password" : "tomi+123"

}

###
GET localhost:9999/users/1